#include<bits/stdc++.h>
using namespace std;


int main(){

    string text = "CCATTCTACTTAAATGGGCGGTCCTTATATCAAGAGCACGGTTCCAACGGCGCCTCGTCCGTTGAATAGGAATCTGGTCACCGCTAACTCATAACTATTTCGCCTAGTTAGCGGACGACCAGGGTTGCGTGTCTGTGCTGGGTTGCTTTCAGCCTTATGTATTAACATAGGGCTACACAACCCATTCGAGTTGAGAGATACAAACTAAGGTGGACGGTTCTCTTGCTATATTCTGTGGCCTGGGAAAAGAATTCACCTTTAATCTGTCAAAGAGTTGATCCCGAGCTCACTAAGATACACAATCCGTGCCATAATACTAGTCCCCTCTCACGGTTGAAGTTAATGGGAACCGTGAAGATTGCGGGGGCGATGTAATCCAACATCTAACTCAACACTATCGATCTGGGTCGTCGTGAGCCATATCTTTTCGGGGATAGATCACGATGTGAAAAGAGAGCCAATTACTGTGGATGGAGCAACCGTTCAGAACAATTATATCACCGCGACGTCCTTAAGCCAGTCGTGGTAGGTTGTCAGTGTTCCCGGGGGAACTGGACCAATCGTCCTTGCACTTTGTCCCTATATTGCCGCTCTAGGAACTTCACGAATGCTGATGCCTGTGCTTCCTGAATACCTGGGTGATGCAGGCACAGAGGCCCAAACGTCGTTGTTATTTCGATTACTTTCTCCGAACTCCAATTCTCTGTGGTGATTAGCGAACATCCTTATACTAGAGGATTTTGAGCATGGGCCCCTATCGGACCGCTGCGTGAACGGAATCCTCTTGATCCTAGCCGGCACATCCTAGGATTGATAACAGCTCATAAATACGTTTTGTAAAATGTCGTCGTAGACTCCGTCCTTAAAGGATGCACATTGTGACGGTAGAGTATACAAGAACAGATGCAAAGGCCGATCCCGGGCTCTAAAATACGGCTCAACTCGCAAGCATGGACGGAGATGCGCTTCCAGTGGGCTGGGCTACGGTATCGCCCGCAGA";
    int k = 12;
    vector<vector<float>> profMatrix = {{0.241, 0.253, 0.253, 0.217, 0.277, 0.145, 0.193, 0.253, 0.289, 0.205, 0.205, 0.277},
                                       {0.241, 0.205, 0.229, 0.205, 0.205, 0.313, 0.229, 0.325, 0.241, 0.289, 0.217, 0.253},
                                       {0.217, 0.325, 0.193, 0.277, 0.301, 0.325, 0.325, 0.181, 0.265, 0.205, 0.277, 0.253},
                                       {0.301, 0.217, 0.325, 0.301, 0.217, 0.217, 0.253, 0.241, 0.205, 0.301, 0.301, 0.217}};

    float prob = -1;
    string ans;

    for(int i = 0; i <= text.size()-k; i++){

        string pattern = text.substr(i, k);
        float currProb = 1;

        for(int j = 0; j < pattern.size(); j++){
            if(pattern[j] == 'A'){
                currProb *= profMatrix[0][j];
            }
            else if(pattern[j] == 'C'){
                currProb *= profMatrix[1][j];
            }
            else if(pattern[j] == 'G'){
                currProb *= profMatrix[2][j];
            }
            else if(pattern[j] == 'T'){
                currProb *= profMatrix[3][j];
            }
        }
    
        if(currProb > prob){
            ans = pattern;
            prob = currProb;
        }
    }

    cout<<ans;
}